### ISSUE TITLE
Add Alert Covid-19

### ISSUE THREAD

**Issue by renanbastos93** [abuuzayr/coronavirus-apps#15]
Alert COVID-19 is a small multiplatform tool written in Golang to help keep you informed about the current situation of COVID-19 in your region, while you stay safe at home.

https://github.com/renanbastos93/alertcovid19

**Comment by abuuzayr** [comment]
Hi @renanbastos93 this is great work! Thank you so much for sharing. 

The intention for this list is however more for applications that the end user can access easily, not just developers. Have you added it to [awesome-coronavirus](https://github.com/soroushchehresa/awesome-coronavirus)?

**Comment by renanbastos93** [comment]
> Hi @renanbastos93 this is great work! Thank you so much for sharing.
> 
> The intention for this list is however more for applications that the end user can access easily, not just developers. Have you added it to [awesome-coronavirus](https://github.com/soroushchehresa/awesome-coronavirus)?

Thanks a lot, I will do
