### ISSUE TITLE
i have made an app about the coronavirus

### ISSUE THREAD

**Issue by R4yGM** [abuuzayr/coronavirus-apps#2]
Hi,
a week ago i developed an app with xamarin about the virus and finally google play published it,
now i found this repository and i was interested if you can app my app.
link : https://play.google.com/store/apps/details?id=com.R4yan.CoronavirusTracker
rayan.

**Comment by abuuzayr** [comment]
Nicely done @R4yGM ! 

I have added it, stay safe over there in :it:

**Comment by abuuzayr** [comment]
@R4yGM I think your app was taken down by Google 😢

**Comment by R4yGM** [comment]
@abuuzayr yeah it got taken down by google twice :( , but now am trying to publish it on amazon app store
