### ISSUE TITLE
Coronavirus tracker app for iOS with map & charts

### ISSUE THREAD

**Issue by mhdhejazi** [abuuzayr/coronavirus-apps#4]
Here you go: https://github.com/MhdHejazi/Corona

Note: the app isn't published on the App Store as [Apple is rejecting coronavirus apps that aren’t from health organizations](https://www.cnbc.com/2020/03/05/apple-rejects-coronavirus-apps-that-arent-from-health-organizations.html).

**Comment by abuuzayr** [comment]
Thanks and nice work @MhdHejazi ! 

Sorry for the late response. It looks like an awesome app, but yes sadly Apple is taking a hard stand on this. 

I'll add it on the list anyway, perhaps someone might find it useful.

**Comment by abuuzayr** [comment]
Added!
