### ISSUE TITLE
Add Virus Ticker Widget Android App

### ISSUE THREAD

**Issue by MG-ng** [abuuzayr/coronavirus-apps#5]
Hi, 
I would appreciate if you would add my new android app which can display useful websites in fullscreen and also displays the amount of infected/deaths/recovered people of a certain country in a widget on the home screen. 

Here are the sources: 
https://github.com/MG-ng/Virus-Ticker-Widget

**Comment by abuuzayr** [comment]
Nicely done @MG-ng ! Thank you for your contribution. 

Is this also live on the App Store?

**Comment by MG-ng** [comment]
No, it is for Android. 

I have already tried to upload it in the Google Play Store but it was blocked before it was even public, unfortunately.
