### ISSUE TITLE
Add CLI Category and Add my CLI Tracker

### ISSUE THREAD

**Issue by warengonzaga** [abuuzayr/coronavirus-apps#7]
Hi,

I would like to suggest a CLI tracker in this list and include my project...
https://github.com/WarenGonzaga/covid19-tracker-cli

and here's the blog for it...
https://warengonza.ga/covid19-tracker-cli

Thanks!

**Comment by abuuzayr** [comment]
wow this is amazing! 

thanks for letting me know, i’ll add it in and leave a ⭐️ !

**Comment by warengonzaga** [comment]
> wow this is amazing!
> 
> thanks for letting me know, i’ll add it in and leave a ⭐️ !

Thank you bro!
